#1 렌딩페이지 퍼블리싱 완료
mobi-community/mobi-ttak-kong pull request #6
Opened 2023-10-04 08:07 UTC by zivivle

## 이슈 번호
#1 

## 작업 분류

- [ ] 버그 수정
- [x] 퍼블리싱
- [ ] 신규 기능
- [ ] 프로젝트 구조 변경
- [ ] 기타

## 작업 상세 내용

1. 헤더 퍼블리싱 완료 
- layout.tsx에 적용해놨습니다. 
- "/intro"에 접속시에만 Header의 background 컬러의 opacity가 0이 됩니다.
- 그외 페이지 접속시 Header의 background 컬러는 white 입니다.

2. 렌딩(인트로 페이지) 퍼블리싱 완료

## 다음 할 일
-  이미지 추가 및 변경을 진행하여 퍼블리싱 완전하게 완료할 생각입니다.

## 체크 리스트
- [x] main 브랜치 pull 받기
- [x] 아직 작업 중인 파일은 올리지 않기

## 질문 사항

💬 **질문이 있어요!**

🔴 **이건 반드시 확인해 주세요!**

2023-10-04 09:03 UTC, Doeunnkimm requested changes
리뷰 남겼습니다 😆 
아 추가로 커밋 단위가 너무 큰 것 같아요 🥲 컴포넌트 단위 혹은 파일 단위로 잘게 커밋해주셨으면 합니다!!..

2023-10-04 09:03 UTC, Doeunnkimm commented on src/config/main.ts
config 파일이라기 보다는 `constants`폴더에 있어야 할 거 같네용 !

2023-10-04 09:03 UTC, Doeunnkimm commented on src/config/sectionFirst.ts
> +      description2: `스터디부터 보고 싶어요.”`,
아 이걸 description1,2로 하신거구나! 줄바꿈을 의도하신거라면 `<br />`를 문자열에 포함하고 렌더링 시에 인식할 수 있도록 하는 방법이 있어요! 찾아보시면 좋을 거 같아용

2023-10-04 09:07 UTC, zivivle commented on src/app/intro/_components/CarouselButton/CarouselButton.tsx
넵 커밋 단위를 더 작게하겠습니다!
props로 number 변수 받아서 반복문 돌리는 것으로 수정하겠습니다!
페이지에 따라 좀 더 진한색으로 bgColor 주는 게 어떤걸 말씀하시는 걸까요???

2023-10-04 09:09 UTC, Doeunnkimm commented on src/app/intro/_components/CarouselButton/CarouselButton.tsx
클릭하면 렌딩 페이지 내에서 이동할 수 있게 하는 기능이요! 작성해주신 코드만 보았을 때는 어떻게 처리하실 지는 아직 작성 안 하신건가! 해서 여쭤봤어요!

2023-10-04 09:10 UTC, zivivle commented on src/app/intro/_components/CarouselButton/CarouselButton.tsx
넵 아직 기능구현은 하지않았습니다! 
나의 스터디 페이지까지 퍼블리싱 완료되면 바로 진행하겠습니다!

2023-10-04 09:18 UTC, zivivle commented on src/app/intro/_components/CarouselButton/CarouselButton.tsx
수정 완료하였습니다!

2023-10-04 09:19 UTC, zivivle commented on src/app/intro/_components/IntroSectionFirst/IntroSectionFirst.tsx
> +          <InfoCard key={index} info={info} />
와 몰랐던 사실이네요! 감사합니다 수정해서 적용하겠습니다

2023-10-04 09:27 UTC, zivivle commented on src/app/intro/_components/IntroSectionFirst/IntroSectionFirst.tsx
> +          <InfoCard key={index} info={info} />
수정 완료하였습니다!

2023-10-04 09:28 UTC, zivivle commented on src/app/intro/_components/IntroSectionFirst/_components/InfoCard/InfoCard.tsx
> +export const InfoCard = ({ info }: { info: InfoType }) => {
type이 프로퍼티 하나짜리 객체라 하더라도 나중을 위해 따로 선언해 주는 것이 좋다는게 어떤 말씀이신지 이해를 못했습니다! 
혹시 어떤 방식인걸까요?
변수명은 수정하도록 하겠습니다 :) 자세한 리뷰 감사합니다

2023-10-04 09:56 UTC, zivivle commented on src/app/intro/_components/IntroSectionFirst/_components/InfoCard/InfoCard.tsx
> +export const InfoCard = ({ info }: { info: InfoType }) => {
변수명 수정 완료하였습니다!

2023-10-04 10:02 UTC, zivivle commented on src/app/intro/_components/IntroSectionSecond/IntroSectionSecond.tsx
> +      <InfoListR />
ㅎㅎ 적용했습니다 감사합니다

2023-10-04 10:04 UTC, zivivle commented on src/app/intro/_components/IntroSectionSecond/_components/InfoListL/InfoListL.tsx
> +import test from '../../../../../../../public/image/intro-screen1.png'
넵 해당 파일을 삭제해서 다음에 이런상황이 또 생기면 적용해보겠습니다!

2023-10-04 10:07 UTC, zivivle commented on src/config/main.ts
수정 하였습니다 :)

2023-10-04 11:08 UTC, zivivle commented on src/app/intro/_components/IntroSectionSecond/_components/InfoListL/InfoListL.tsx
> +import test from '../../../../../../../public/image/intro-screen1.png'
적용했습니다! 감사합니다 :)

2023-10-04 11:26 UTC, zivivle commented on src/app/intro/_components/IntroSectionThird/IntroSectionThird.tsx
> +      }}
수정 완료하였습니다.

2023-10-04 11:36 UTC, Doeunnkimm requested changes
변경사항 확인하고 추가 리뷰 남겨요 ! 😆

2023-10-04 11:36 UTC, Doeunnkimm commented on src/config/sectionFirst.ts
> +      id: 3,
id를 추가하지 않고 image 경로 같은 경우 unique하니까 `key={info.image}`해도 충분할 거 같아요!

2023-10-04 11:36 UTC, Doeunnkimm commented on src/app/intro/_components/IntroSectionSecond/IntroSectionSecond.tsx
> +      </div>
prop으로 position 같은 값을 넘겨서 통째로 추상화를 해보는 거 어떨까요 ?
position: 'left' | 'right'로 해서 postion에 따라 이미지와 글씨가 왼/오로 해서 !

2023-10-04 11:36 UTC, Doeunnkimm commented on src/app/intro/_components/IntroSectionFirst/IntroSectionFirst.tsx
배럴 파일이 필요해요 !! ✨

2023-10-04 11:43 UTC, zivivle commented on src/config/sectionFirst.ts
> +      id: 3,
info.image로 해볼려고 했는데 StaticImageData 형식이라서 key값으로 안된다고 하네용

2023-10-04 11:46 UTC, zivivle commented on src/app/intro/_components/IntroSectionFirst/IntroSectionFirst.tsx
오잉 배럴 파일이 다 있는데 왜 안올라갔을까요

2023-10-04 12:15 UTC, zivivle commented on src/app/intro/_components/IntroSectionFirst/_components/InfoCard/infoCard.types.ts
> +  description2: string
이부분 나중에 다시 여쭤봐도 될까요?

2023-10-05 04:44 UTC, Doeunnkimm commented on src/app/intro/_components/IntroSectionFirst/_components/InfoCard/infoCard.types.ts
> +  description2: string
요건 제가 description1, 2가 서로 다른 거구나 파악하고 리뷰를 남겼던 건데 아래 코드를 보니 줄바꿈 때문에 나눠두셨구나를 알았습니다..!!! 아래 리뷰로 반영해주시면 감사하겠습니당

2023-10-05 04:48 UTC, Doeunnkimm commented on src/config/sectionFirst.ts
> +      id: 3,
description1,2를 하나로 합친 description으로 만드시면 그걸로 key에 넣으셔도 될 거 같아요!

2023-10-05 04:49 UTC, Doeunnkimm commented on src/app/intro/_components/IntroSectionSecond/IntroSectionSecond.tsx
> +      </div>
어떤 커밋 내역에 있는지 알려주실 수 있나요 ..? 
보통 한 리뷰와 관련하여 변경사항이 발생하면 커밋 내역을 걸어두면 편합니다!

[fix: constants 파일들 수정, 이미지 경로 수정](https://github.com/mobi-community/mobi-ttak-kong/pull/6/commits/39f91a035e2ba0dc2cb56cc5d90b65592c327363)

요렇게 말이죠!

2023-10-05 04:51 UTC, Doeunnkimm requested changes
궁금한 점이 있어서 리뷰 남깁니다! 🤔

2023-10-05 04:51 UTC, Doeunnkimm commented on src/constants/sectionSecond.constants.ts
> +export type SectionSecondConstants = typeof sectionSecondConstants
요건 어디서 사용하시는데 여기에 선언하신 건지 알 수 있을까요 ?? !

2023-10-05 04:51 UTC, Doeunnkimm commented on src/constants/sectionFirst.constants.ts
> +export type SectionFirstConstants = typeof sectionFirstConstants
요것두 궁금해요~!

2023-10-05 05:06 UTC, zivivle commented on src/config/sectionFirst.ts
> +      id: 3,
<br />로 시도해봤는데 적용이 안되네요 “저와 딱맞는 스터디원를 <br /> 쉽게 찾기가 어려워요.” 이렇게 뜨는데 이유가 있을까요?

2023-10-05 05:08 UTC, zivivle commented on src/app/intro/_components/IntroSectionSecond/IntroSectionSecond.tsx
> +      </div>
[feat: ImageCardPair 컴포넌트 생성](https://github.com/mobi-community/mobi-ttak-kong/pull/6/commits/4bdbc9f8bd6eae2e4d7709458d37d94990399fb1)
입니다 :)!!

2023-10-05 05:10 UTC, Doeunnkimm commented on src/config/sectionFirst.ts
> +      id: 3,
```tsx
<div dangerouslySetInnerHTML={{ __html: LEVEL_DATA[level].description }} />
```

이렇게 string 값을 넣어주면 `<br />`도 인식되어 줄바꿈이 잘 됩니다! 😆

2023-10-05 05:10 UTC, Doeunnkimm commented on src/app/intro/_components/IntroSectionSecond/IntroSectionSecond.tsx
> +      </div>
왕! 너무 깔끔해요 대만죡 🤩

2023-10-06 02:59 UTC, Doeunnkimm approved these changes

2023-10-06 04:32 UTC, merged